version: '3.4'

services:
  educationsystem.rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

  educationsystem.studentmanagement.db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"

  educationsystem.studentmanagement.api:
    image: ${DOCKER_REGISTRY-}educationsystemstudentmanagementapi
    build:
      context: .
      dockerfile: EducationSystem.StudentManagement.Api/Dockerfile
    depends_on:
    - educationsystem.studentmanagement.db
    - educationsystem.rabbitmq

  educationsystem.groupmanagement.api:
    image: ${DOCKER_REGISTRY-}educationsystemgroupmanagementapi
    build:
      context: .
      dockerfile: EducationSystem.GroupManagement.Api/Dockerfile
    depends_on:
    - educationsystem.rabbitmq

